# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tcvectordb.rpc.proto.olama_pb2 as olama__pb2


class SearchEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.setAlias = channel.unary_unary(
                '/alias/set',
                request_serializer=olama__pb2.AddAliasRequest.SerializeToString,
                response_deserializer=olama__pb2.UpdateAliasResponse.FromString,
                )
        self.getAlias = channel.unary_unary(
                '/alias/delete',
                request_serializer=olama__pb2.GetAliasRequest.SerializeToString,
                response_deserializer=olama__pb2.GetAliasResponse.FromString,
                )
        self.deleteAlias = channel.unary_unary(
                '/alias/delete',
                request_serializer=olama__pb2.RemoveAliasRequest.SerializeToString,
                response_deserializer=olama__pb2.UpdateAliasResponse.FromString,
                )
        self.createCollection = channel.unary_unary(
                '/collection/create',
                request_serializer=olama__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=olama__pb2.CreateCollectionResponse.FromString,
                )
        self.dropCollection = channel.unary_unary(
                '/collection/drop',
                request_serializer=olama__pb2.DropCollectionRequest.SerializeToString,
                response_deserializer=olama__pb2.DropCollectionResponse.FromString,
                )
        self.truncateCollection = channel.unary_unary(
                '/collection/truncate',
                request_serializer=olama__pb2.TruncateCollectionRequest.SerializeToString,
                response_deserializer=olama__pb2.TruncateCollectionResponse.FromString,
                )
        self.describeCollection = channel.unary_unary(
                '/collection/describe',
                request_serializer=olama__pb2.DescribeCollectionRequest.SerializeToString,
                response_deserializer=olama__pb2.DescribeCollectionResponse.FromString,
                )
        self.listCollections = channel.unary_unary(
                '/collection/list',
                request_serializer=olama__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=olama__pb2.ListCollectionsResponse.FromString,
                )
        self.rebuildIndex = channel.unary_unary(
                '/index/rebuild',
                request_serializer=olama__pb2.RebuildIndexRequest.SerializeToString,
                response_deserializer=olama__pb2.RebuildIndexResponse.FromString,
                )
        self.upsert = channel.unary_unary(
                '/document/upsert',
                request_serializer=olama__pb2.UpsertRequest.SerializeToString,
                response_deserializer=olama__pb2.UpsertResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/document/update',
                request_serializer=olama__pb2.UpdateRequest.SerializeToString,
                response_deserializer=olama__pb2.UpdateResponse.FromString,
                )
        self.query = channel.unary_unary(
                '/document/query',
                request_serializer=olama__pb2.QueryRequest.SerializeToString,
                response_deserializer=olama__pb2.QueryResponse.FromString,
                )
        self.search = channel.unary_unary(
                '/document/search',
                request_serializer=olama__pb2.SearchRequest.SerializeToString,
                response_deserializer=olama__pb2.SearchResponse.FromString,
                )
        self.hybrid_search = channel.unary_unary(
                '/document/hybridSearch',
                request_serializer=olama__pb2.SearchRequest.SerializeToString,
                response_deserializer=olama__pb2.SearchResponse.FromString,
                )
        self.full_text_search = channel.unary_unary(
                '/olama.SearchEngine/full_text_search',
                request_serializer=olama__pb2.SearchRequest.SerializeToString,
                response_deserializer=olama__pb2.SearchResponse.FromString,
                )
        self.dele = channel.unary_unary(
                '/document/delete',
                request_serializer=olama__pb2.DeleteRequest.SerializeToString,
                response_deserializer=olama__pb2.DeleteResponse.FromString,
                )
        self.range_search = channel.unary_unary(
                '/olama.SearchEngine/range_search',
                request_serializer=olama__pb2.SearchRequest.SerializeToString,
                response_deserializer=olama__pb2.SearchResponse.FromString,
                )
        self.sort = channel.unary_unary(
                '/olama.SearchEngine/sort',
                request_serializer=olama__pb2.SortRequest.SerializeToString,
                response_deserializer=olama__pb2.SortResponse.FromString,
                )
        self.explain = channel.unary_unary(
                '/olama.SearchEngine/explain',
                request_serializer=olama__pb2.ExplainRequest.SerializeToString,
                response_deserializer=olama__pb2.ExplainResponse.FromString,
                )
        self.count = channel.unary_unary(
                '/document/count',
                request_serializer=olama__pb2.CountRequest.SerializeToString,
                response_deserializer=olama__pb2.CountResponse.FromString,
                )
        self.createDatabase = channel.unary_unary(
                '/database/create',
                request_serializer=olama__pb2.DatabaseRequest.SerializeToString,
                response_deserializer=olama__pb2.DatabaseResponse.FromString,
                )
        self.dropDatabase = channel.unary_unary(
                '/database/drop',
                request_serializer=olama__pb2.DatabaseRequest.SerializeToString,
                response_deserializer=olama__pb2.DatabaseResponse.FromString,
                )
        self.listDatabases = channel.unary_unary(
                '/database/list',
                request_serializer=olama__pb2.DatabaseRequest.SerializeToString,
                response_deserializer=olama__pb2.DatabaseResponse.FromString,
                )
        self.describeDatabase = channel.unary_unary(
                '/olama.SearchEngine/describeDatabase',
                request_serializer=olama__pb2.DescribeDatabaseRequest.SerializeToString,
                response_deserializer=olama__pb2.DescribeDatabaseResponse.FromString,
                )
        self.user_create = channel.unary_unary(
                '/olama.SearchEngine/user_create',
                request_serializer=olama__pb2.UserAccountRequest.SerializeToString,
                response_deserializer=olama__pb2.UserAccountResponse.FromString,
                )
        self.user_drop = channel.unary_unary(
                '/olama.SearchEngine/user_drop',
                request_serializer=olama__pb2.UserAccountRequest.SerializeToString,
                response_deserializer=olama__pb2.UserAccountResponse.FromString,
                )
        self.user_change_password = channel.unary_unary(
                '/olama.SearchEngine/user_change_password',
                request_serializer=olama__pb2.UserAccountRequest.SerializeToString,
                response_deserializer=olama__pb2.UserAccountResponse.FromString,
                )
        self.user_grant = channel.unary_unary(
                '/olama.SearchEngine/user_grant',
                request_serializer=olama__pb2.UserPrivilegesRequest.SerializeToString,
                response_deserializer=olama__pb2.UserPrivilegesResponse.FromString,
                )
        self.user_revoke = channel.unary_unary(
                '/olama.SearchEngine/user_revoke',
                request_serializer=olama__pb2.UserPrivilegesRequest.SerializeToString,
                response_deserializer=olama__pb2.UserPrivilegesResponse.FromString,
                )
        self.user_list = channel.unary_unary(
                '/olama.SearchEngine/user_list',
                request_serializer=olama__pb2.UserListRequest.SerializeToString,
                response_deserializer=olama__pb2.UserListResponse.FromString,
                )
        self.user_describe = channel.unary_unary(
                '/olama.SearchEngine/user_describe',
                request_serializer=olama__pb2.UserDescribeRequest.SerializeToString,
                response_deserializer=olama__pb2.UserDescribeResponse.FromString,
                )
        self.get_version = channel.unary_unary(
                '/olama.SearchEngine/get_version',
                request_serializer=olama__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=olama__pb2.GetVersionResponse.FromString,
                )
        self.modifyVectorIndex = channel.unary_unary(
                '/index/modifyVectorIndex',
                request_serializer=olama__pb2.ModifyVectorIndexRequest.SerializeToString,
                response_deserializer=olama__pb2.ModifyVectorIndexResponse.FromString,
                )
        self.addIndex = channel.unary_unary(
                '/index/add',
                request_serializer=olama__pb2.AddIndexRequest.SerializeToString,
                response_deserializer=olama__pb2.AddIndexResponse.FromString,
                )
        self.dropIndex = channel.unary_unary(
                '/index/drop',
                request_serializer=olama__pb2.DropIndexRequest.SerializeToString,
                response_deserializer=olama__pb2.DropIndexResponse.FromString,
                )


class SearchEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def setAlias(self, request, context):
        """修改别名指向
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAlias(self, request, context):
        """查询别名指向
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteAlias(self, request, context):
        """删除别名指向
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createCollection(self, request, context):
        """创建索引
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dropCollection(self, request, context):
        """删除索引
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def truncateCollection(self, request, context):
        """清空索引
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def describeCollection(self, request, context):
        """显示索引配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listCollections(self, request, context):
        """显示全部索引
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rebuildIndex(self, request, context):
        """重建索引
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def upsert(self, request, context):
        """写入向量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """更新向量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def query(self, request, context):
        """查询向量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def search(self, request, context):
        """KNN搜索
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def hybrid_search(self, request, context):
        """混合搜索
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def full_text_search(self, request, context):
        """全文搜索
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dele(self, request, context):
        """删除向量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def range_search(self, request, context):
        """范围搜索
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sort(self, request, context):
        """指定候选集排序
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def explain(self, request, context):
        """explain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def count(self, request, context):
        """count
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createDatabase(self, request, context):
        """创建 database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dropDatabase(self, request, context):
        """删除 database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listDatabases(self, request, context):
        """显示全部 database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def describeDatabase(self, request, context):
        """显示数据库
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def user_create(self, request, context):
        """RBAC相关接口
        创建用户
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def user_drop(self, request, context):
        """删除用户
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def user_change_password(self, request, context):
        """修改用户密码
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def user_grant(self, request, context):
        """授予用户角色或权限
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def user_revoke(self, request, context):
        """撤销用户角色或权限
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def user_list(self, request, context):
        """展示所有用户列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def user_describe(self, request, context):
        """展示某个用户的详细信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_version(self, request, context):
        """获取版本（api升级兼容性考虑）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def modifyVectorIndex(self, request, context):
        """修改index配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addIndex(self, request, context):
        """新增scalar的索引
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dropIndex(self, request, context):
        """删除scalar的索引
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'setAlias': grpc.unary_unary_rpc_method_handler(
                    servicer.setAlias,
                    request_deserializer=olama__pb2.AddAliasRequest.FromString,
                    response_serializer=olama__pb2.UpdateAliasResponse.SerializeToString,
            ),
            'getAlias': grpc.unary_unary_rpc_method_handler(
                    servicer.getAlias,
                    request_deserializer=olama__pb2.GetAliasRequest.FromString,
                    response_serializer=olama__pb2.GetAliasResponse.SerializeToString,
            ),
            'deleteAlias': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteAlias,
                    request_deserializer=olama__pb2.RemoveAliasRequest.FromString,
                    response_serializer=olama__pb2.UpdateAliasResponse.SerializeToString,
            ),
            'createCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.createCollection,
                    request_deserializer=olama__pb2.CreateCollectionRequest.FromString,
                    response_serializer=olama__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'dropCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.dropCollection,
                    request_deserializer=olama__pb2.DropCollectionRequest.FromString,
                    response_serializer=olama__pb2.DropCollectionResponse.SerializeToString,
            ),
            'truncateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.truncateCollection,
                    request_deserializer=olama__pb2.TruncateCollectionRequest.FromString,
                    response_serializer=olama__pb2.TruncateCollectionResponse.SerializeToString,
            ),
            'describeCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.describeCollection,
                    request_deserializer=olama__pb2.DescribeCollectionRequest.FromString,
                    response_serializer=olama__pb2.DescribeCollectionResponse.SerializeToString,
            ),
            'listCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.listCollections,
                    request_deserializer=olama__pb2.ListCollectionsRequest.FromString,
                    response_serializer=olama__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'rebuildIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.rebuildIndex,
                    request_deserializer=olama__pb2.RebuildIndexRequest.FromString,
                    response_serializer=olama__pb2.RebuildIndexResponse.SerializeToString,
            ),
            'upsert': grpc.unary_unary_rpc_method_handler(
                    servicer.upsert,
                    request_deserializer=olama__pb2.UpsertRequest.FromString,
                    response_serializer=olama__pb2.UpsertResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=olama__pb2.UpdateRequest.FromString,
                    response_serializer=olama__pb2.UpdateResponse.SerializeToString,
            ),
            'query': grpc.unary_unary_rpc_method_handler(
                    servicer.query,
                    request_deserializer=olama__pb2.QueryRequest.FromString,
                    response_serializer=olama__pb2.QueryResponse.SerializeToString,
            ),
            'search': grpc.unary_unary_rpc_method_handler(
                    servicer.search,
                    request_deserializer=olama__pb2.SearchRequest.FromString,
                    response_serializer=olama__pb2.SearchResponse.SerializeToString,
            ),
            'hybrid_search': grpc.unary_unary_rpc_method_handler(
                    servicer.hybrid_search,
                    request_deserializer=olama__pb2.SearchRequest.FromString,
                    response_serializer=olama__pb2.SearchResponse.SerializeToString,
            ),
            'full_text_search': grpc.unary_unary_rpc_method_handler(
                    servicer.full_text_search,
                    request_deserializer=olama__pb2.SearchRequest.FromString,
                    response_serializer=olama__pb2.SearchResponse.SerializeToString,
            ),
            'dele': grpc.unary_unary_rpc_method_handler(
                    servicer.dele,
                    request_deserializer=olama__pb2.DeleteRequest.FromString,
                    response_serializer=olama__pb2.DeleteResponse.SerializeToString,
            ),
            'range_search': grpc.unary_unary_rpc_method_handler(
                    servicer.range_search,
                    request_deserializer=olama__pb2.SearchRequest.FromString,
                    response_serializer=olama__pb2.SearchResponse.SerializeToString,
            ),
            'sort': grpc.unary_unary_rpc_method_handler(
                    servicer.sort,
                    request_deserializer=olama__pb2.SortRequest.FromString,
                    response_serializer=olama__pb2.SortResponse.SerializeToString,
            ),
            'explain': grpc.unary_unary_rpc_method_handler(
                    servicer.explain,
                    request_deserializer=olama__pb2.ExplainRequest.FromString,
                    response_serializer=olama__pb2.ExplainResponse.SerializeToString,
            ),
            'count': grpc.unary_unary_rpc_method_handler(
                    servicer.count,
                    request_deserializer=olama__pb2.CountRequest.FromString,
                    response_serializer=olama__pb2.CountResponse.SerializeToString,
            ),
            'createDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.createDatabase,
                    request_deserializer=olama__pb2.DatabaseRequest.FromString,
                    response_serializer=olama__pb2.DatabaseResponse.SerializeToString,
            ),
            'dropDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.dropDatabase,
                    request_deserializer=olama__pb2.DatabaseRequest.FromString,
                    response_serializer=olama__pb2.DatabaseResponse.SerializeToString,
            ),
            'listDatabases': grpc.unary_unary_rpc_method_handler(
                    servicer.listDatabases,
                    request_deserializer=olama__pb2.DatabaseRequest.FromString,
                    response_serializer=olama__pb2.DatabaseResponse.SerializeToString,
            ),
            'describeDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.describeDatabase,
                    request_deserializer=olama__pb2.DescribeDatabaseRequest.FromString,
                    response_serializer=olama__pb2.DescribeDatabaseResponse.SerializeToString,
            ),
            'user_create': grpc.unary_unary_rpc_method_handler(
                    servicer.user_create,
                    request_deserializer=olama__pb2.UserAccountRequest.FromString,
                    response_serializer=olama__pb2.UserAccountResponse.SerializeToString,
            ),
            'user_drop': grpc.unary_unary_rpc_method_handler(
                    servicer.user_drop,
                    request_deserializer=olama__pb2.UserAccountRequest.FromString,
                    response_serializer=olama__pb2.UserAccountResponse.SerializeToString,
            ),
            'user_change_password': grpc.unary_unary_rpc_method_handler(
                    servicer.user_change_password,
                    request_deserializer=olama__pb2.UserAccountRequest.FromString,
                    response_serializer=olama__pb2.UserAccountResponse.SerializeToString,
            ),
            'user_grant': grpc.unary_unary_rpc_method_handler(
                    servicer.user_grant,
                    request_deserializer=olama__pb2.UserPrivilegesRequest.FromString,
                    response_serializer=olama__pb2.UserPrivilegesResponse.SerializeToString,
            ),
            'user_revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.user_revoke,
                    request_deserializer=olama__pb2.UserPrivilegesRequest.FromString,
                    response_serializer=olama__pb2.UserPrivilegesResponse.SerializeToString,
            ),
            'user_list': grpc.unary_unary_rpc_method_handler(
                    servicer.user_list,
                    request_deserializer=olama__pb2.UserListRequest.FromString,
                    response_serializer=olama__pb2.UserListResponse.SerializeToString,
            ),
            'user_describe': grpc.unary_unary_rpc_method_handler(
                    servicer.user_describe,
                    request_deserializer=olama__pb2.UserDescribeRequest.FromString,
                    response_serializer=olama__pb2.UserDescribeResponse.SerializeToString,
            ),
            'get_version': grpc.unary_unary_rpc_method_handler(
                    servicer.get_version,
                    request_deserializer=olama__pb2.GetVersionRequest.FromString,
                    response_serializer=olama__pb2.GetVersionResponse.SerializeToString,
            ),
            'modifyVectorIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.modifyVectorIndex,
                    request_deserializer=olama__pb2.ModifyVectorIndexRequest.FromString,
                    response_serializer=olama__pb2.ModifyVectorIndexResponse.SerializeToString,
            ),
            'addIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.addIndex,
                    request_deserializer=olama__pb2.AddIndexRequest.FromString,
                    response_serializer=olama__pb2.AddIndexResponse.SerializeToString,
            ),
            'dropIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.dropIndex,
                    request_deserializer=olama__pb2.DropIndexRequest.FromString,
                    response_serializer=olama__pb2.DropIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'olama.SearchEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearchEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def setAlias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/setAlias',
            olama__pb2.AddAliasRequest.SerializeToString,
            olama__pb2.UpdateAliasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAlias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/getAlias',
            olama__pb2.GetAliasRequest.SerializeToString,
            olama__pb2.GetAliasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteAlias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/deleteAlias',
            olama__pb2.RemoveAliasRequest.SerializeToString,
            olama__pb2.UpdateAliasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/createCollection',
            olama__pb2.CreateCollectionRequest.SerializeToString,
            olama__pb2.CreateCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def dropCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/dropCollection',
            olama__pb2.DropCollectionRequest.SerializeToString,
            olama__pb2.DropCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def truncateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/truncateCollection',
            olama__pb2.TruncateCollectionRequest.SerializeToString,
            olama__pb2.TruncateCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def describeCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/describeCollection',
            olama__pb2.DescribeCollectionRequest.SerializeToString,
            olama__pb2.DescribeCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/listCollections',
            olama__pb2.ListCollectionsRequest.SerializeToString,
            olama__pb2.ListCollectionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def rebuildIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/rebuildIndex',
            olama__pb2.RebuildIndexRequest.SerializeToString,
            olama__pb2.RebuildIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def upsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/upsert',
            olama__pb2.UpsertRequest.SerializeToString,
            olama__pb2.UpsertResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/update',
            olama__pb2.UpdateRequest.SerializeToString,
            olama__pb2.UpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/query',
            olama__pb2.QueryRequest.SerializeToString,
            olama__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/search',
            olama__pb2.SearchRequest.SerializeToString,
            olama__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def hybrid_search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/hybrid_search',
            olama__pb2.SearchRequest.SerializeToString,
            olama__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def full_text_search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/full_text_search',
            olama__pb2.SearchRequest.SerializeToString,
            olama__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def dele(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/dele',
            olama__pb2.DeleteRequest.SerializeToString,
            olama__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def range_search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/range_search',
            olama__pb2.SearchRequest.SerializeToString,
            olama__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/sort',
            olama__pb2.SortRequest.SerializeToString,
            olama__pb2.SortResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def explain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/explain',
            olama__pb2.ExplainRequest.SerializeToString,
            olama__pb2.ExplainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def count(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/count',
            olama__pb2.CountRequest.SerializeToString,
            olama__pb2.CountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/createDatabase',
            olama__pb2.DatabaseRequest.SerializeToString,
            olama__pb2.DatabaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def dropDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/dropDatabase',
            olama__pb2.DatabaseRequest.SerializeToString,
            olama__pb2.DatabaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listDatabases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/listDatabases',
            olama__pb2.DatabaseRequest.SerializeToString,
            olama__pb2.DatabaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def describeDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/describeDatabase',
            olama__pb2.DescribeDatabaseRequest.SerializeToString,
            olama__pb2.DescribeDatabaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def user_create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/user_create',
            olama__pb2.UserAccountRequest.SerializeToString,
            olama__pb2.UserAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def user_drop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/user_drop',
            olama__pb2.UserAccountRequest.SerializeToString,
            olama__pb2.UserAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def user_change_password(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/user_change_password',
            olama__pb2.UserAccountRequest.SerializeToString,
            olama__pb2.UserAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def user_grant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/user_grant',
            olama__pb2.UserPrivilegesRequest.SerializeToString,
            olama__pb2.UserPrivilegesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def user_revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/user_revoke',
            olama__pb2.UserPrivilegesRequest.SerializeToString,
            olama__pb2.UserPrivilegesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def user_list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/user_list',
            olama__pb2.UserListRequest.SerializeToString,
            olama__pb2.UserListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def user_describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/user_describe',
            olama__pb2.UserDescribeRequest.SerializeToString,
            olama__pb2.UserDescribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/get_version',
            olama__pb2.GetVersionRequest.SerializeToString,
            olama__pb2.GetVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def modifyVectorIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/modifyVectorIndex',
            olama__pb2.ModifyVectorIndexRequest.SerializeToString,
            olama__pb2.ModifyVectorIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def addIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/addIndex',
            olama__pb2.AddIndexRequest.SerializeToString,
            olama__pb2.AddIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def dropIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/olama.SearchEngine/dropIndex',
            olama__pb2.DropIndexRequest.SerializeToString,
            olama__pb2.DropIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
